apimServiceName: prod-apim-cicd
namedValues:
  - name: demonamevalue
    properties:
      displayName: demonamevalue
      value: "https://www.search2.com"
  - name: demonamevalue2
    properties:
      displayName: demonamevalue2
      keyVault:
        identityClientId: 9b177356-0cf1-4303-913b-e6581ceeb77b
        secretIdentifier: https://keyvault-cicd.vault.azure.net/secrets/prod-kv-demo-rk/77836a15cb31426ca4d995d12168bed1
loggers:
diagnostics:
backends:
apis:
